# Travis CI build configuration

language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    #- build-tools-19.1.0
    #- build-tools-20.0.0
    - build-tools-22.0.1

    - android-22
    #- android-19
    #- android-18

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22

# Explicitly disable build caching
cache: false

# Tell commands to behave, add bintray key
env:
  global:
    - TERM=dumb
    - secure: "gvLrkWptaosqPOfsc7tEATO7ectB5fVXRLQiwHk3wZZ2aF+j3ayisMr5UzDHOHj6P5VDSv1c6fz0P8jr89k2Er5nWmwDjSAVOPdc4Hi9VAxUo/lLlyTtvO4KG1mXYSR/lr5UvxehvUaaPw3g8YLyO/WTzN9Kayw0Qh/q1HAEePo="

# Build
script:
  - ./ci/build.sh
  - ./ci/release.sh
