# Travis CI build configuration

language:
  - java
jdk:
  - oraclejdk7

# Explicitly disable build caching
cache: false

# Tell commands to behave, add bintray key
env:
  global:
    - TERM=dumb
    - secure: "gvLrkWptaosqPOfsc7tEATO7ectB5fVXRLQiwHk3wZZ2aF+j3ayisMr5UzDHOHj6P5VDSv1c6fz0P8jr89k2Er5nWmwDjSAVOPdc4Hi9VAxUo/lLlyTtvO4KG1mXYSR/lr5UvxehvUaaPw3g8YLyO/WTzN9Kayw0Qh/q1HAEePo="

# Prep
before_install:
  - ./ci/prepare.sh

# Disable travis gradle fiddling
install:
  - true

# Build
script:
  - ./ci/build.sh
  - ./ci/release.sh
