#/bin/bash
set -e

# 64-bit Linux needs some packages to execute Android tools
if [ `uname` == 'Linux' ] && [ `uname -m` = x86_64 ]; then
	echo "Installing Linux 64-bit packages"
	sudo apt-get update -qq
	sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null
fi

#
# Hack: Plugin does not download all deps yet.
# Let gradle plugin download SDK (rather than scripting ourselves), then add deps manually.
#

# First build, will always fail until plugin is fixed
echo "Installing Android SDK..."
(
	set +e
	./gradlew 2>/dev/null | grep "SDK"
)

# Find SDK location (generated by plugin) and prepare update flags
export ANDROID_HOME=`cat local.properties | grep sdk.dir | cut -f 2 -d "="`
export PATH=$PATH:$ANDROID_HOME/tools
export UPDATE="android update sdk --no-ui --force --all --filter"

# Install desired packages
echo "Downloading additional packages..."
echo yes | $UPDATE platform-tools               > /dev/null
echo yes | $UPDATE build-tools-22.0.1           > /dev/null
echo yes | $UPDATE android-22                   > /dev/null
echo yes | $UPDATE extra-android-support        > /dev/null
echo yes | $UPDATE extra-android-m2repository   > /dev/null

# At this point, SDK has all required components & we're ready to build.
